adding topic5 excercises
Jarekubicki/DevOps pull request #1
Opened 2023-01-25 18:40 UTC by Jarekubicki

2023-01-25 18:41 UTC, kpuda commented on src/tematyka5/excercies/Task5_17/Playlist.java
> +    public static void main(String[] args) {
first pr comment

2023-01-26 07:46 UTC, kpuda requested changes

2023-01-26 07:46 UTC, kpuda commented on src/tematyka5/excercies/Task5_17/DataInput.java
> +    public String enterAlbumName() {
fajnie, że wyciągnąłeś taką funkcjonalność do nowego "serwisu".

2023-01-26 07:46 UTC, kpuda commented on src/tematyka5/excercies/Task5_17/DataInput.java
> +        return albumName = input.nextLine();
deklarowanie tej zmiennej w 12 linijce jest w tym wypadku zbędne. Można od razu powołać się na scanner - czyli return input.nextLine();

2023-01-26 07:46 UTC, kpuda commented on src/tematyka5/excercies/Task5_10/NumbersArray.java
dobrze zauważyłeś myk z liczbą 0.

Zamiast dodawać +1 w pętlach można zrobić pętle, której i=1, a warunek wygląda tak: i<=array.length .

Aby zautomatyzować to zadanie powinniśmy się pozbyć funkcji warunkowych w środku pętli.

Dodatkowo aby podnieść liczbę do potęgi możemy użyć wbudowanej biblioteki Math i skorzystać z metody Math.pow()

2023-01-26 07:46 UTC, kpuda commented on src/tematyka5/excercies/Task5_13/AppTest.java
>  import java.util.ArrayList;
dobrze napisane. Musiałbyś się jeszcze uchronić na sam koniec od NullPointerException. Jeśli user od razu wpisze STOP to linijki od 24 w dół zepsują nam program. Trzeba by tam dorobić funkcję warunkową sprawdzającą wielkość listy.

Jeśli chodzi o konwencję nazywania zmiennych drukowanymi literami (linia 11) to takie zmienne są zazwyczaj statyczne

2023-01-26 07:46 UTC, kpuda commented on src/tematyka5/excercies/Task5_15/ColorTest.java
> +package tematyka5.excercies.Task5_15;
Przekombinowane zadanie z enumami :) Zmień na String.

W 12 linijce zadeklaruj Listę, która posiada wszystkie te kolory zamiast tablicy.

Podoba mi się, że tworzysz metody ale na ten moment są one jeszcze niepotrzebne (już nie długo). Te operacje, które są tam wykonywane spokojnie mogą być w obrębie psvm.

Żeby posortować set danych można użyć wbudowanej klasy Collections.sort().
To samo tyczy się odwracania kolejności: Collections.reverse()

2023-01-26 07:46 UTC, kpuda commented on src/tematyka5/excercies/Task5_18/Playlist.java
> +        switch (userTaskToPerform) {
ogólnie spoko. Jeśli chciałbyś dodać funkcjonalność, która pozwala w kółko coś zmieniać to musiałbyś użyć pętli while, która powtarza te czynności aż user nie wprowadzi np. 4

2023-01-26 16:55 UTC, Jarekubicki commented on src/tematyka5/excercies/Task5_10/NumbersArray.java
> Aby zautomatyzować to zadanie powinniśmy się pozbyć funkcji warunkowych w środku pętli.

Nie do końca wiem o co chodzi. Czy trzeba wydzielić te warunki do odrębnych funkcji? Bo przesunięcie ich poza pętlę spowoduje, że będą pominięte w trakcie uzupełniania tabeli danymi.

2023-01-26 17:10 UTC, Jarekubicki commented on src/tematyka5/excercies/Task5_13/AppTest.java
>  import java.util.ArrayList;
Zrobione. Dodałem warunek sprawdzający czy lista nie jest pusta i jeśli wynik = true to wykonujemy poszczególne operacje na liście.
Funkcja sprawdzająca wielkość liter? AppTest.java - linijka 22 ?

2023-01-26 18:02 UTC, Jarekubicki commented on src/tematyka5/excercies/Task5_15/ColorTest.java
> +package tematyka5.excercies.Task5_15;
Done.

2023-01-26 18:03 UTC, Jarekubicki commented on src/tematyka5/excercies/Task5_18/Playlist.java
> +        switch (userTaskToPerform) {
W sumie to zadanie mówiło o stworzeniu prostego menu ale faktycznie miałem w planach trochę to rozwinąć.

2023-01-27 08:56 UTC, kpuda requested changes

2023-01-27 08:56 UTC, kpuda commented on src/tematyka5/excercies/Task5_10/NumbersArray.java
na ten moment, przez zastosowanie funkcji warunkowych jesteśmy uwiązani na sztywno do implementacji, która wykorzystuje tylko 3 wartości. W momencie kiedy doszedłby 4 wiersz w tablicy musiałbyś dodać kolejnego else ifa z wartością 4.

Możesz się pozbyć wszystkich ifów i zastosować Math.pow(i,j).

2023-01-27 08:56 UTC, kpuda commented on src/tematyka5/excercies/Task5_20/ColorsCollection.java
> +        HashSet<String> colorsSet = new HashSet<>(Set.copyOf(colorsArray));
można się pozbyć Set.copyOf()

2023-01-27 08:56 UTC, kpuda commented on src/tematyka5/excercies/Task5_20/ColorsCollection.java
> +            System.out.println(colors);
można iterować pętlą albo zrobić souta colorsSet.toString()

2023-01-27 08:57 UTC, kpuda commented on src/tematyka5/excercies/Task5_18/Playlist.java
> +        switch (userTaskToPerform) {
zadanie dobre, dodałem taką dygresję :)

2023-01-27 12:03 UTC, kpuda requested changes

2023-01-27 12:03 UTC, kpuda commented on src/tematyka5/excercies/Task5_10/NumbersArray.java
musisz zrobić pętlę int i=1;i<=array.length;i++, a druga to j=1;j<=array[i].length 

Robiąc to możesz podkładać normalnie i oraz j bez modyfikacji

2023-02-08 18:09 UTC, merged