tematyka6 added for approval
Jarekubicki/DevOps pull request #2
Opened 2023-02-08 18:05 UTC by Jarekubicki

2023-02-09 08:04 UTC, kpuda requested changes

2023-02-09 08:04 UTC, kpuda commented on src/tematyka6/excercises/Task6_12/Manager.java
> +    public boolean checkIfOrderOnList(HashMap<Order, Integer> orderList, Order orderToCheck) {
ta metoda spokojnie może być prywatna, ponieważ jest używana wyłącznie w środku tej klasy. Ponadto możesz się pozbyć pierwszego parametru metody (orderList) i powołać się od razu na pole z 11 linijki

2023-02-11 15:53 UTC, Jarekubicki commented on src/tematyka6/excercises/Task6_5/Vehicle.java
> +        return mileage + kilometers;
Poprawione.

2023-02-11 15:53 UTC, Jarekubicki commented on src/tematyka6/excercises/Task6_12/Manager.java
> +    public boolean checkIfOrderOnList(HashMap<Order, Integer> orderList, Order orderToCheck) {
Poprawione.

2023-02-22 17:18 UTC, kpuda approved these changes

2023-02-22 18:16 UTC, merged