tematyka7 added for approval
Jarekubicki/DevOps pull request #3
Opened 2023-02-08 19:48 UTC by Jarekubicki

2023-02-09 08:10 UTC, kpuda requested changes

2023-02-09 08:10 UTC, kpuda commented on src/tematyka7/excercises/Task7_9/Deck.java
> +                deck.add(card);
Wyciągnij tablicę SUITES i VALUES tutaj albo zadeklaruj je jako statyczne tak aby możliwe było powołanie się na nie bez konieczności inicjalizowania obiektu typu Card. 

Następnie będziesz mógł się pozbyć linijek 21-24 i zastąpić je jednym wyrażeniem:
deck.add(new Card(Card.getSuites()[i],Card.getValues()[j]);

2023-02-11 16:04 UTC, Jarekubicki commented on src/tematyka7/excercises/Task7_9/Deck.java
> +                deck.add(card);
Takie pytanie - w które miejsce powinienem wyciągnąć te 2 tablice?

2023-02-11 16:10 UTC, kpuda commented on src/tematyka7/excercises/Task7_9/Deck.java
> +                deck.add(card);
W sumie to zadeklaruj metody getSuites/Values jako statyczne i powołasz się na nie w lini 21/22 bez tworzenia obiektu z lini 13. Ten obiekt i tak nigdzie nie jest później wykorzystywany

2023-02-22 18:35 UTC, kpuda approved these changes

2023-02-22 18:36 UTC, merged