Feature/tematyka8
Jarekubicki/DevOps pull request #4
Opened 2023-02-08 21:07 UTC by Jarekubicki

2023-02-09 08:20 UTC, kpuda requested changes

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/Vehicle.java
> +    Depot depot;
zmienne muszą być "protected" tak aby mogły być dziedzioczne "poza paczką". Zmienną depot ma być nazwa zajezdni - czyli obiekt typu String

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/Depot.java
> +    String name;
modyfikator dostępu

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/Depot.java
> +
depot powinien mieć również listę obiektów typu Vehicle, którą odziedziczą tramDepot oraz busDepot

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/BusDepot.java
> +        super(name);
BusDepot zawsze będzie mieć nazwę Bus Depot więc możemy się pozbyć parametru "name" i na sztywno wpisać "Bus Depot".

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/BusDepot.java
> +    ArrayList<Bus> busesAssignedToDepot;
BusDepot potrzebuje zmiennej dot. miesięcznego zużycia paliwa

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/TramDepot.java
> +    public TramDepot(String name, ArrayList<Tramway> tramListAssignedToDepot) {
TramDepot zawsze będzie mieć nazwę Tram Depot więc możemy się pozbyć parametru "name" i na sztywno wpisać "Tram Depot".

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/TramDepot.java
> +    ArrayList<Tramway> tramListAssignedToDepot;
TramDepot potrzebuje zmiennej dot. liczby wagoników

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_6/Person.java
> +    String name;
modyfikatory dostępu

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_6/Professor.java
> +    int salary;
modyfikator dostępu

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_6/Student.java
> +    int studentNumber;
modyfikatory dostępu

2023-02-09 08:20 UTC, kpuda commented on src/tematyka8/excercises/Task8_6/Student.java
> +        return true;
trzeba sprawdzić czy średnia jest np. powyżej 3

2023-02-11 16:10 UTC, Jarekubicki commented on src/tematyka8/excercises/Task8_2/Shape.java
> +
Rozumiem, tylko co gdy będziemy chcieli policzyć pole dla innej figury, np. koła. Wtedy znika uniwersalność tej klasy. W kole nie szerokości ani długości.

2023-02-11 16:25 UTC, Jarekubicki commented on src/tematyka8/excercises/Task8_4/TramDepot.java
> +    ArrayList<Tramway> tramListAssignedToDepot;
Wydawało mi się, że to tramwaj ma wiedzieć ile ma wagoników, nie depot. Prośba o potwierdzenie.

2023-02-11 16:30 UTC, kpuda commented on src/tematyka8/excercises/Task8_2/Shape.java
> +
Okej, zwracam honor :) Nie wiem dlaczego wydawało mi się, że w poleceniu zadania jest podane, że Shape ma length oraz height. Masz rację

2023-02-11 16:32 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/TramDepot.java
> +    ArrayList<Tramway> tramListAssignedToDepot;
Każdy tramwaj składa się od 1 do 3 wagoników. Dodatkowo zajezdnia ma wiedzieć ile w sumie jest wagoników:
"Zajezdnia autobusowa podaje dodatkowo sumaryczne zużycie paliwa w bieżącym miesiącu, a tramwajowa ogólną liczbę wagonów."

2023-02-11 16:42 UTC, Jarekubicki commented on src/tematyka8/excercises/Task8_4/BusDepot.java
> +        super(name);
Ale pkt 9 i 10 zadania. Ja to zrozumiałem tak, że każda zajezdnia wie jakiego typu pojazdy mogą w niej stać (dlatego rozróżnienie na tramDepot i busDepot). Oprócz tego każda zajezdnia ma nazwę (ja nadałem przypadkowo NorthDepot). Prośba o info zrotne.

2023-02-11 16:53 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/BusDepot.java
> +        super(name);
9. Każda zajezdnia wie jakie pojazdy do niej należą - czyli tworząc w mainie (Test) pojazd dodajesz go do odpowiedniej zajezdni, po czym metoda z zajezdni zwraca w konsoli wszystkie dostępne pojazdy z danej zajezdni. Korzystając z dziedziczenia możemy wykorzystać listę z klasy Vehicle ale możemy to zostawić na zajęcia

10. Każda zajezdnia ma nazwę - w takim razie niech zostanie. Trochę inaczej zrozumiałem ten punkt, a jak wiemy w programowaniu nie ma jednej poprawnej odpowiedzi :)

2023-02-11 19:32 UTC, Jarekubicki commented on src/tematyka8/excercises/Task8_4/BusDepot.java
> +        super(name);
Poddaję się Krzysztofie. Wydawało mi się,  że ogarnąłem to zadanie ale po Twoich uwagach utknąłem. Sorry.

2023-02-11 23:13 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/BusDepot.java
> +        super(name);
Zajezdnia ma posiadać takie pola jak nazwa oraz lista pojazdów. Dodatkowo powinna zawierać metodę, w której zostaną zwrócone informacje o niej. 

Można też dorobić metodę typu addVehicle() w której dodasz pojazd do listy. Dzięki temu, że bus i tramwaj dziedziczy po vehicle, będzie można wykorzystać odziedziczoną listę. 

Zajezdnia autobusowa ma zawierać dodatkowe pole nt zużycia paliwa. Za każdym razem kiedy wywołasz metodę addVehicle powinien zostać dodany autobus do listy oraz pole dot. zużycia paliwa powinno się powiększyć o spalanie zadeklarowane w busie. 

Zajezdnia tramwajowa powinna zawierać pole nt całościowej ilości wagoników wszystkich tramwajów w zajezdni . Za każdym wywołaniem metody addVehicle zmienna dot wagoników powinna sie powiększyć o ilosc wagoników dodanego tramwaju

2023-02-11 23:14 UTC, kpuda commented on src/tematyka8/excercises/Task8_4/BusDepot.java
> +        super(name);
Zrobimy to szybko na spotkaniu raz dwa :)

2023-02-22 18:48 UTC, kpuda approved these changes

2023-02-22 18:49 UTC, merged